version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo Zipping Lambda code...
      - zip -r function.zip .

artifacts:
  files:
    - function.zip
